SELECT
COLUMN_1,
COLUMN_2,
COLUMN_3,
COLUMN_4,
COLUMN_5,
COLUMN_6 AS COL_6,
COLUMN_7 AS COL_7,
COLUMN_8 AS COL_8,
COLUMN_9 AS COL_9
FROM BASE AS BASE
INNER JOIN DT_TEMP.SAMPLE_DB AS A
ON BASE.PKEY = A.PKEY
